<a href="https://colab.research.google.com/github/Prachijainn24/summer-pandas_numpy/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#data science
#problem => data acquire => data storage(data engineer)=>
#data preparation=>info extracted(data analysis(python,stats,sql))=> data visualization
#ML and algorithm (chatbot,open ai services,open cv,NLP) => data report
#data scientists

In [ ]:
#python libraries - pandas and numpy(numeric python) [help in data prepration in form of numbers]
#scientific library -> data in form of nd array

panadas- data manipulations,export data

In [ ]:
#need to import to numpy

In [ ]:
import numpy
numpy.arange(4)

array([0, 1, 2, 3])

In [ ]:
import numpy
type( numpy.arange(7)  )

numpy.ndarray

In [ ]:
import numpy as np
arr1=np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [ ]:
np.ndarray(3)

array([0. , 0.5, 1. ])

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
arr1=np.array([1,2,3])
arr1.size

3

In [ ]:
#1d array
arr1=np.array([ [1,2],[3,4],[5,6] ])
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

6
(3, 2)
int64


In [ ]:
arr2=np.arange(3)
print(arr2.shape) #states rows and columns
print(arr1.dtype)

(3,)
int64


In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

numpy reshape

In [ ]:
arr1=np.arange(9)
arr1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

numpy transpose

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
b=a.transpose()
print(b)

[[1 3]
 [2 4]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
b=a.transpose()
print(b)

[[1 3 5]
 [2 4 6]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
arr1.ndim

1

In [ ]:
import numpy as np
arr1=np.array( [[1.0,2,3],[3,4,3],[5,6,4] ] )
arr1.ndim

2

numpy string =>convert => int

panda = powerful library used to clean the data and tranform it according to user


In [ ]:
#series=1d array
#dataframe= collection of series
#dataframe= a kind of tabulary form of data

In [ ]:
import pandas as pd

series = pd.Series([10, 2, 34, 4])
print(series)

0    10
1     2
2    34
3     4
dtype: int64


In [ ]:
series[0] = 90
print(series[0])   #updated


90


In [ ]:
series.max()
print(series.idxmin() )

1


In [ ]:
import pandas as pd

series = pd.Series([10, 2, 34, 4], index=["A", "B", "C", "D"])  # customize index
print(series.to_dict())


{'A': 10, 'B': 2, 'C': 34, 'D': 4}


In [ ]:
arr1=np.array([10,13,15,19,2])
series=pd.Series(arr1)
type(series)

pandas.core.series.Series

In [ ]:
arr1=np.array([10,13,15,19,2])
series=pd.Series(arr1)
series.value_counts(ascending=True)

10    1
13    1
15    1
19    1
2     1
Name: count, dtype: int64

In [ ]:
series.is_unique #do we unique value or not

False

In [ ]:
series=pd.Series( [10,13,15,19,24,16,12,10] )
series.value_counts(ascending=True)
series.sort_values()

0    10
7    10
6    12
1    13
2    15
5    16
3    19
4    24
dtype: int64

In [ ]:
series=pd.Series( [10,13,15,19,24,16,12,10] )
series.value_counts(ascending=False)
series.sort_values()

0    10
7    10
6    12
1    13
2    15
5    16
3    19
4    24
dtype: int64

In [ ]:
arr1=np.array([10,13,15,19,2,15])
series=pd.Series(arr1)
series.drop_duplicates()

0    10
1    13
2    15
3    19
4     2
dtype: int64

In [ ]:
arr1=np.array([10,13,15,19,2,15])
series=pd.Series(arr1)
series.drop_duplicates(inplace=True)    #original change converted

In [ ]:
mydictionary={"A":10,"B":20,"C":30}
series=pd.Series(mydictionary)
print(series.to_dict())

{'A': 10, 'B': 20, 'C': 30}


In [ ]:
mydictionary={"A":10,"B":20,"C":30,"D":20}
series=pd.Series(mydictionary)
series.drop_duplicates()

A    10
B    20
C    30
dtype: int64

In [ ]:
mydictionary={"A":10,"B":20,"C":30,"D":20}
pd.Series(mydictionary)
series.drop_duplicates(inplace=True)

In [ ]:
mydictionary={"A":10,"B":20,"C":30,"D":20}
series.value_counts(ascending=True)
series.sort_values()


A    10
B    20
C    30
dtype: int64

In [ ]:
data=[ [10,20,12],[11,16,29] ]
pd.DataFrame(data)           #multiple columns selected

0   1   2
0  10  20  12
1  11  16  29

In [ ]:
data=[ [10,20,12],[11,16,29] ]
df=pd.DataFrame(data,columns=["product1","product2","product3"] )

In [ ]:
type(df["product1"])

pandas.core.series.Series

In [ ]:
#read_csv through pandas
import pandas as pd

df = pd.read_csv('/content/movies.csv')
print(df)

      movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                  

In [ ]:
#read csv file in pandas and select one column and count how many time the value is present here.

#top3 value shown based on file

#count no. of values you have


#drop dupicate values from any column

#change integer column to float

In [ ]:
#read_csv through pandas
import pandas as pd

df = pd.read_csv('/content/movies.csv')
print(df)

      movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                  

In [ ]:

# Select one column and count how many times each value appears
genre_counts = df['genres'].value_counts()
print(genre_counts)

genres
Drama                                        1053
Comedy                                        946
Comedy|Drama                                  435
Comedy|Romance                                363
Drama|Romance                                 349
                                             ... 
Children|Drama|Musical                          1
Adventure|Drama|Horror|Mystery|Thriller         1
Adventure|Children|Comedy|Fantasy|Mystery       1
Adventure|Animation|Children|Western            1
Comedy|Mystery|Romance|Thriller                 1
Name: count, Length: 951, dtype: int64


In [ ]:
 #Top 3
top_3_genres = genre_counts.head(3)
print(top_3_genres)

genres
Drama           1053
Comedy           946
Comedy|Drama     435
Name: count, dtype: int64


In [ ]:
#count no. of values you have
total_unique_genres = df['genres'].nunique()
print(total_unique_genres)

951


In [ ]:
#drop dupicate values from any column
df_unique_titles = df.drop_duplicates(subset='title')
print(df_unique_titles)

      movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                  

In [ ]:
# column from integer to float
df['movieId'] = df['movieId'].astype(float)
print(df['movieId'] )

0            1.0
1            2.0
2            3.0
3            4.0
4            5.0
          ...   
9737    193581.0
9738    193583.0
9739    193585.0
9740    193587.0
9741    193609.0
Name: movieId, Length: 9742, dtype: float64
